//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiThu
    {
        public int id { get; set; }
        public int soBiThu { get; set; }
        public string danhSachDien { get; set; }
        public System.DateTime ngay { get; set; }
        public int soDien { get; set; }
    }
}
