//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DienMatDaPhanPhoi
    {
        public int ID { get; set; }
        public string LuuFile { get; set; }
        public string FileDinhKem { get; set; }
        public string NoiGui { get; set; }
        public string TrichYeu { get; set; }
        public string DoMat { get; set; }
        public string DoMatFile { get; set; }
        public Nullable<int> MaDienMat { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string GhiChu { get; set; }
        public string Loai { get; set; }
        public int SoBaoMat { get; set; }
        public Nullable<int> BanIn { get; set; }
        public System.DateTime NgayIn { get; set; }
        public string NguoiDuyet { get; set; }
        public string NguoiKy { get; set; }
        public string ChucDanh { get; set; }
        public byte[] ChuKy { get; set; }
    }
}
