//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiemChungDien
    {
        public int id { get; set; }
        public string TenNoiNhan { get; set; }
        public string DanhSachDien { get; set; }
        public int SoBiThu { get; set; }
        public Nullable<int> TongSoTrang { get; set; }
        public Nullable<int> idNoiNhan { get; set; }
    
        public virtual NoiNhan NoiNhan { get; set; }
    }
}
