//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDuyet
    {
        public int id { get; set; }
        public string TenNguoiDuyet { get; set; }
        public Nullable<bool> MacDinh { get; set; }
        public byte[] ChuKy { get; set; }
    }
}
