//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NoiNhan()
        {
            this.KiemChungDiens = new HashSet<KiemChungDien>();
        }
    
        public int id { get; set; }
        public string MaNoiNhan { get; set; }
        public string TenNoiNhan { get; set; }
        public string Loai { get; set; }
        public int SoBaoMat { get; set; }
        public string Nhom { get; set; }
        public Nullable<int> SoThuTu { get; set; }
        public Nullable<bool> CoBi { get; set; }
        public Nullable<bool> DangHoatDong { get; set; }
        public string CoSo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiemChungDien> KiemChungDiens { get; set; }
    }
}
