//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBNG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMMgEntities : DbContext
    {
        public SMMgEntities()
            : base("name=SMMgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BiThu> BiThus { get; set; }
        public virtual DbSet<CoSo> CoSoes { get; set; }
        public virtual DbSet<DienMat> DienMats { get; set; }
        public virtual DbSet<DienMatTemp> DienMatTemps { get; set; }
        public virtual DbSet<FileDinhKemDienMat> FileDinhKemDienMats { get; set; }
        public virtual DbSet<KiemChungDien> KiemChungDiens { get; set; }
        public virtual DbSet<Loai> Loais { get; set; }
        public virtual DbSet<NoiGui> NoiGuis { get; set; }
        public virtual DbSet<NoiNhan> NoiNhans { get; set; }
        public virtual DbSet<NoiNhanTemp> NoiNhanTemps { get; set; }
        public virtual DbSet<NguoiDuyet> NguoiDuyets { get; set; }
        public virtual DbSet<NguoiKy> NguoiKies { get; set; }
        public virtual DbSet<Nhom> Nhoms { get; set; }
        public virtual DbSet<PemisionDetail> PemisionDetails { get; set; }
        public virtual DbSet<Permision> Permisions { get; set; }
        public virtual DbSet<PhanLoaiNoiNhan> PhanLoaiNoiNhans { get; set; }
        public virtual DbSet<TuyChinh> TuyChinhs { get; set; }
        public virtual DbSet<TuyChinhCombobox> TuyChinhComboboxes { get; set; }
        public virtual DbSet<TrangThai> TrangThais { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<DienMatDaPhanPhoi> DienMatDaPhanPhois { get; set; }
    }
}
