//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyChinh
    {
        public int id { get; set; }
        public Nullable<double> VanBanLeTrai { get; set; }
        public Nullable<double> VanBanLeTren { get; set; }
        public Nullable<double> DsnLeTrai { get; set; }
        public Nullable<double> DsnLeTren { get; set; }
        public Nullable<double> DsnDanDong { get; set; }
        public Nullable<double> DauChimRong { get; set; }
        public Nullable<double> DauChimCao { get; set; }
        public Nullable<double> DauChimFont { get; set; }
        public Nullable<double> DauChimOpacity { get; set; }
        public Nullable<double> DauChimMauDoc { get; set; }
        public Nullable<double> DauChimMauPdf { get; set; }
        public Nullable<double> VungCkRong { get; set; }
        public Nullable<double> VungCkCao { get; set; }
        public Nullable<double> VungCkLeDuoi { get; set; }
        public Nullable<double> AnhCkRong1 { get; set; }
        public Nullable<double> AnhCkCao1 { get; set; }
        public Nullable<double> AnhCkCao2 { get; set; }
        public Nullable<double> AnhCkRong2 { get; set; }
        public string TieuDe { get; set; }
        public string In2Mat { get; set; }
        public string KhayGiay { get; set; }
        public string Dien { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> InDauMatLenDien { get; set; }
        public string CoSo { get; set; }
        public string LuuFile { get; set; }
    }
}
