using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.XtraGrid.Views.Grid;
using System.Diagnostics;
using ProjectBNG.Models;

namespace ProjectBNG
{
    public delegate void OnSaveNguoiNhan(List<NoiNhan> nguoinhan);

    public partial class frmAddPrinting : Form
    {
        public OnSaveNguoiNhan OnSubmitForm;
        public List<NoiNhan> listNoiNhan = new List<NoiNhan>();
        public frmAddPrinting()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.NoiNhans.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                noiNhansBindingSource2.DataSource = dbContext.NoiNhans.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void button1_Click(object sender, EventArgs e)
        {
            listNoiNhan.Clear();
            NoiNhan item = null;

            foreach (var a in this.gridView1.GetSelectedRows())
            {
                item = (NoiNhan)this.gridView1.GetRow(a);
                listNoiNhan.Add(item);
            }
            if (listNoiNhan.Count > 0)
            {   
                OnSubmitForm.Invoke(listNoiNhan);
            }
            this.Close();
        }

        private void frmAddPrinting_Load(object sender, EventArgs e)
        {
            gridView1.OptionsSelection.MultiSelectMode = GridMultiSelectMode.CheckBoxRowSelect;
        }
    }
}
