using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.XtraGrid.Views.Grid;
using ProjectBNG.Models;
using ProjectBNG.Class;

namespace ProjectBNG
{
    public partial class frmDienPhanPhoi : Form
    {
        public frmDienPhanPhoi()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //// ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.DienMats.LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    try
            //    {
            //        //dienMatsBindingSource.DataSource = dbContext.DienMats.Local.ToBindingList();
            //        //dienMatsBindingSource.DataSource = dbContext.DienMats.Select(m => new
            //        //{
            //        //    id = m.ID,
            //        //    NguoiIn=m.NguoiIn.
            //        //}).ToList();
            //        dienMatsBindingSource.DataSource = dbContext.ViewDienMats.Local.ToBindingList();
            //    }
            //    catch { }
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.DienMats.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                dienMatsBindingSource1.DataSource = dbContext.DienMats.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            dateTimePickerTuNgay.Value = DateTime.Today.AddDays(-30);
            try
            {

            cbxNoiGui.DataSource = dbContext.NoiGuis.ToList();
            cbxNoiGui.DisplayMember = "Ten";
                cbxNoiGui.SelectedIndex = -1;
            cbxNoiNhan.DataSource = dbContext.DienMats.Local.ToBindingList();
            cbxNoiNhan.DisplayMember = "DsNoiNhan";
                cbxNoiNhan.SelectedIndex = -1;
            }
            catch { }
        }

        private bool cal(int _Width, GridView _View)
        {
            _View.IndicatorWidth = _View.IndicatorWidth < _Width ? _Width : _View.IndicatorWidth;
            return true;
        }

        private void btnDong_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void gridViewDienPhanPhoi_CustomDrawRowIndicator(object sender, RowIndicatorCustomDrawEventArgs e)
        {
            CommonFunction.gridView_CustomDrawRowIndicator(sender, e, gridViewDienPhanPhoi);
        }

        SMMgEntities db = new SMMgEntities();

        private void btnXoa_Click(object sender, EventArgs e)
        {
            DialogResult wr = MessageBox.Show("Xóa điện mật ?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (wr == DialogResult.Yes)
            {
                DienMat delDienMat = new DienMat();
                try
                {

                    delDienMat.ID = int.Parse(gridViewDienPhanPhoi.GetRowCellValue(gridViewDienPhanPhoi.FocusedRowHandle, "ID").ToString());
                }
                catch
                {
                }
                deleteNoiNhan(delDienMat);
                gridControlBaoCao_Load(sender, e);
                MessageBox.Show("Xóa thành công ", "Thông báo");
            }
            void deleteNoiNhan(DienMat dienMat)
            {
                DienMat d = db.DienMats.Find(dienMat.ID);
                db.DienMats.Remove(d);
                db.SaveChanges();
            }
        }

        private void gridControlBaoCao_Load(object sender, EventArgs e)
        {
            gridControlBaoCao.DataSource = db.DienMats.ToList();
            gridControlBaoCao.RefreshDataSource();
        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            SMMgEntities db = new SMMgEntities();
            try
            { 
                if(cbxNoiGui.Text== "--select--")
                {

                }
                if(cbxNoiNhan.Text== "--select--")
                {

                }
                //gridControlBaoCao.DataSource = db.DienMats
                //        .Where(x => x.TrangThai == cmbTrangThai.Text)
                //        .Select(x => new
                //        {
                //            NameUser = x.NameUser,
                //            Username = x.Username,
                //            PerUser = x.PerUser,
                //        }).ToList();
                //gridControlBaoCao.RefreshDataSource();
            }
            catch
            {
            }
        }
    }
}
