using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.XtraGrid.Views.Grid;
using ProjectBNG.Models;
using ProjectBNG.Class;

namespace ProjectBNG
{
    public partial class frmDienPhanPhoi : Form
    {
        public frmDienPhanPhoi()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //// ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.DienMats.LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    try
            //    {
            //        //dienMatsBindingSource.DataSource = dbContext.DienMats.Local.ToBindingList();
            //        //dienMatsBindingSource.DataSource = dbContext.DienMats.Select(m => new
            //        //{
            //        //    id = m.ID,
            //        //    NguoiIn=m.NguoiIn.
            //        //}).ToList();
            //        dienMatsBindingSource.DataSource = dbContext.ViewDienMats.Local.ToBindingList();
            //    }
            //    catch { }
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.DienMats.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                dienMatsBindingSource1.DataSource = dbContext.DienMats.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

           
        }

        private bool cal(int _Width, GridView _View)
        {
            _View.IndicatorWidth = _View.IndicatorWidth < _Width ? _Width : _View.IndicatorWidth;
            return true;
        }

        private void btnDong_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void gridViewDienPhanPhoi_CustomDrawRowIndicator(object sender, RowIndicatorCustomDrawEventArgs e)
        {
            CommonFunction.gridView_CustomDrawRowIndicator(sender, e, gridViewDienPhanPhoi);
        }

        SMMgEntities db = new SMMgEntities();

        private void btnXoa_Click(object sender, EventArgs e)
        {
            DialogResult wr = MessageBox.Show("Xóa điện mật ?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (wr == DialogResult.Yes)
            {
                DienMat delDienMat = new DienMat();
                try
                {

                    delDienMat.ID = int.Parse(gridViewDienPhanPhoi.GetRowCellValue(gridViewDienPhanPhoi.FocusedRowHandle, "ID").ToString());
                }
                catch
                {
                }
                deleteNoiNhan(delDienMat);
                gridControlBaoCao_Load(sender, e);
                MessageBox.Show("Xóa thành công ", "Thông báo");
            }
            void deleteNoiNhan(DienMat dienMat)
            {
                DienMat d = db.DienMats.Find(dienMat.ID);
                db.DienMats.Remove(d);
                db.SaveChanges();
            }
        }

        private void gridControlBaoCao_Load(object sender, EventArgs e)
        {
            gridControlBaoCao.DataSource = db.DienMats.ToList();
            gridControlBaoCao.RefreshDataSource();
        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            SMMgEntities db = new SMMgEntities();
            try
            {
                if (cbxNoiGui.Text == "" && cbxNoiNhan.Text == "" && txbSoMat.Text == "" && tbxTrichYeu.Text == "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value)
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiGui.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.NoiGui == cbxNoiGui.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiNhan.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.DsNoiNhan == cbxNoiNhan.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (txbSoMat.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.MaDienMat == int.Parse(txbSoMat.Text) && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (tbxTrichYeu.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.TrichYeu == tbxTrichYeu.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }

                if (cbxNoiGui.Text != "" && cbxNoiNhan.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.NoiGui == cbxNoiGui.Text && x.DsNoiNhan == cbxNoiNhan.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiGui.Text != "" && txbSoMat.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.NoiGui == cbxNoiGui.Text && x.MaDienMat == int.Parse(txbSoMat.Text) && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiGui.Text != "" && tbxTrichYeu.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.NoiGui == cbxNoiGui.Text && x.TrichYeu == tbxTrichYeu.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiNhan.Text != "" && txbSoMat.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.DsNoiNhan == cbxNoiNhan.Text && x.MaDienMat == int.Parse(txbSoMat.Text) && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiNhan.Text != "" && tbxTrichYeu.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.DsNoiNhan == cbxNoiNhan.Text && x.TrichYeu == tbxTrichYeu.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (txbSoMat.Text != "" && tbxTrichYeu.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.MaDienMat == int.Parse(txbSoMat.Text) && x.TrichYeu == tbxTrichYeu.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }

                if (cbxNoiGui.Text != "" && cbxNoiNhan.Text != "" && txbSoMat.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                        .Where(x => x.NoiGui == cbxNoiGui.Text && x.DsNoiNhan == cbxNoiNhan.Text && x.MaDienMat == int.Parse(txbSoMat.Text) && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                        .Select(x => new
                        {
                            MaDienMat = x.MaDienMat,
                            Ngay = x.Ngay,
                            NoiGui = x.NoiGui,
                            DoMat = x.DoMat,
                            DsNoiNhan = x.DsNoiNhan,
                            Trang = x.Trang,
                            BanIn = x.BanIn,
                            TrichYeu = x.TrichYeu,
                            NguoiIn = x.NguoiIn,
                            NgayIn = x.NgayIn,
                            LuuFile = x.LuuFile
                        }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiGui.Text != "" && cbxNoiNhan.Text != "" && tbxTrichYeu.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                       .Where(x => x.NoiGui == cbxNoiGui.Text && x.DsNoiNhan == cbxNoiNhan.Text && x.TrichYeu == tbxTrichYeu.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                       .Select(x => new
                       {
                           MaDienMat = x.MaDienMat,
                           Ngay = x.Ngay,
                           NoiGui = x.NoiGui,
                           DoMat = x.DoMat,
                           DsNoiNhan = x.DsNoiNhan,
                           Trang = x.Trang,
                           BanIn = x.BanIn,
                           TrichYeu = x.TrichYeu,
                           NguoiIn = x.NguoiIn,
                           NgayIn = x.NgayIn,
                           LuuFile = x.LuuFile
                       }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiGui.Text != "" && txbSoMat.Text != "" && tbxTrichYeu.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                       .Where(x => x.NoiGui == cbxNoiGui.Text && x.MaDienMat == int.Parse(txbSoMat.Text) && x.TrichYeu == tbxTrichYeu.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                       .Select(x => new
                       {
                           MaDienMat = x.MaDienMat,
                           Ngay = x.Ngay,
                           NoiGui = x.NoiGui,
                           DoMat = x.DoMat,
                           DsNoiNhan = x.DsNoiNhan,
                           Trang = x.Trang,
                           BanIn = x.BanIn,
                           TrichYeu = x.TrichYeu,
                           NguoiIn = x.NguoiIn,
                           NgayIn = x.NgayIn,
                           LuuFile = x.LuuFile
                       }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
                if (cbxNoiNhan.Text != "" && txbSoMat.Text != "" && tbxTrichYeu.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                       .Where(x => x.DsNoiNhan == cbxNoiNhan.Text && x.MaDienMat == int.Parse(txbSoMat.Text) && x.TrichYeu == tbxTrichYeu.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                       .Select(x => new
                       {
                           MaDienMat = x.MaDienMat,
                           Ngay = x.Ngay,
                           NoiGui = x.NoiGui,
                           DoMat = x.DoMat,
                           DsNoiNhan = x.DsNoiNhan,
                           Trang = x.Trang,
                           BanIn = x.BanIn,
                           TrichYeu = x.TrichYeu,
                           NguoiIn = x.NguoiIn,
                           NgayIn = x.NgayIn,
                           LuuFile = x.LuuFile
                       }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }

                if (cbxNoiGui.Text != "" && cbxNoiNhan.Text != "" && txbSoMat.Text != "" && tbxTrichYeu.Text != "")
                {
                    gridControlBaoCao.DataSource = db.DienMats
                       .Where(x => x.NoiGui == cbxNoiGui.Text && x.DsNoiNhan == cbxNoiNhan.Text && x.MaDienMat == int.Parse(txbSoMat.Text) && x.TrichYeu == tbxTrichYeu.Text && (x.Ngay >= dateTimePickerTuNgay.Value && x.Ngay <= dateTimePickerDenNgay.Value))
                       .Select(x => new
                       {
                           MaDienMat = x.MaDienMat,
                           Ngay = x.Ngay,
                           NoiGui = x.NoiGui,
                           DoMat = x.DoMat,
                           DsNoiNhan = x.DsNoiNhan,
                           Trang = x.Trang,
                           BanIn = x.BanIn,
                           TrichYeu = x.TrichYeu,
                           NguoiIn = x.NguoiIn,
                           NgayIn = x.NgayIn,
                           LuuFile = x.LuuFile
                       }).ToList();
                    gridControlBaoCao.RefreshDataSource();
                }
            }
            catch
            {
            }
        }

        private void frmDienPhanPhoi_Load(object sender, EventArgs e)
        {
            dateTimePickerTuNgay.Value = DateTime.Today.AddDays(-30);
            try
            {
                SMMgEntities dbContext = new SMMgEntities();
                cbxNoiGui.DataSource = dbContext.NoiGuis.ToList();
                cbxNoiGui.DisplayMember = "Ten";
                cbxNoiGui.SelectedIndex = -1;
                cbxNoiNhan.DataSource = dbContext.DienMats.ToList();
                cbxNoiNhan.DisplayMember = "DsNoiNhan";
                cbxNoiNhan.SelectedIndex = -1;
            }
            catch { }
        }

        private void btnThongKe_Click(object sender, EventArgs e)
        {
            //SMMgEntities db = new SMMgEntities();
            //using(frmPrint print=new frmPrint())
            //{
            //    print.PrintClick(db.)
            //}
        }

        private void btnIn_Click(object sender, EventArgs e)
        {

        }

        private void btnInLai_Click(object sender, EventArgs e)
        {

        }
    }
}
