using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using ProjectBNG.Class;
using ProjectBNG.Models;
using System.Diagnostics;

namespace ProjectBNG
{
    public partial class frmKiemChungDien : Form
    {
        public frmKiemChungDien()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.KiemChungDiens.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                // ok thu xem =)
                //try
                //{
                //    //kiemChungDiensBindingSource.DataSource = dbContext.KiemChungDiens.Select(m => new 
                //    //{
                //    //    TenNoiNhan = m.NoiNhan.TenNoiNhan,
                //    //    id = m.id,
                //    //    DanhSachDien = m.DanhSachDien,
                //    //    SoBiThu = m.SoBiThu,
                //    //    TongSoTrang = m.TongSoTrang
                //    //}).ToList();
                //    //kiemChungDiensBindingSource.DataSource = dbContext.ViewKiemChungDiens.Local.ToBindingList();

                //}
                //catch (Exception e) {
                //    Debug.WriteLine("123");

                //}
                kiemChungDiensBindingSource.DataSource= dbContext.KiemChungDiens.Local.ToBindingList();

            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            dateTimePickerTuNgay.Value = DateTime.Today.AddDays(-30);
        }

        private void gridViewKiemChungDien_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
            if (!gridViewKiemChungDien.IsGroupRow(e.RowHandle)) //Nếu không phải là Group
            {
                if (e.Info.IsRowIndicator) //Nếu là dòng Indicator
                {
                    if (e.RowHandle < 0)
                    {
                        e.Info.ImageIndex = 0;
                        e.Info.DisplayText = string.Empty;
                    }
                    else
                    {
                        e.Info.ImageIndex = -1; //Không hiển thị hình
                        e.Info.DisplayText = (e.RowHandle + 1).ToString(); //Số thứ tự tăng dần
                    }

                    //hàm này dùng thay đổi độ rộng mặc định của cột số thứ tự
                    var _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                    var _Width = Convert.ToInt32(_Size.Width) + 20;
                    BeginInvoke(new MethodInvoker(delegate { CommonFunction.cal(_Width, gridViewKiemChungDien); }));
                }
            }
            else
            {
                e.Info.ImageIndex = -1;
                e.Info.DisplayText = string.Format("[{0}]", e.RowHandle * -1); //Nhân -1 để đánh lại số thứ tự tăng dần
                var _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                var _Width = Convert.ToInt32(_Size.Width) + 20;
                BeginInvoke(new MethodInvoker(delegate { CommonFunction.cal(_Width, gridViewKiemChungDien); }));
            }
        }

        private void btnDong_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            SMMgEntities db = new SMMgEntities();
            try
            {
                gridControlKiemChungDien.DataSource = db.KiemChungDiens
                        .Where(x => x.NgayIn > dateTimePickerTuNgay.Value && x.NgayIn < dateTimePickerDenNgay.Value)
                        .Select(x => new
                        {
                            TenNoiNhan=x.TenNoiNhan,
                            DanhSachDien=x.DanhSachDien,
                            TongSoTrang=x.TongSoTrang,
                            SoLuongDien=x.SoLuongDien

                        }).ToList();
                gridControlKiemChungDien.RefreshDataSource();
            }
            catch
            {
            }
        }

    }
}
