using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.Data;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Columns;

namespace ProjectBNG
{
    public partial class frmNguoiDung : Form
    {
        public System.Windows.Forms.Keys Modifiers { get; }
        public frmNguoiDung()
        {
            InitializeComponent();
            
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ProjectBNG.Models.SMMgEntities dbContext = new Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.USERs.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    uSERsBindingSource.DataSource = dbContext.USERs.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private bool CheckExistForm(string name)
        {
            bool check = false;
            foreach (Form frm in this.MdiChildren)
            {
                if (frm.Name == name)
                {
                    check = true;
                    break;
                }
            }
            return check;
        }

        private void ActiveChildForm(string name)
        {
            foreach (Form frm in this.MdiChildren)
            {
                if (frm.Name == name)
                {
                    frm.Activate();
                    break;
                }
            }
        }

        private void button4_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            if (!CheckExistForm("frmThemNguoiDung"))
            {
                frmThemNguoiDung fthemngdung = new frmThemNguoiDung();
                fthemngdung.MdiParent = this.MdiParent;
                fthemngdung.Show();
            }
            else
            {
                ActiveChildForm("frmThemNguoiDung");
            }

        }

        private void btnXoa_Click(object sender,KeyEventArgs e)
        {
           // gridControl1.ProcessGridKey += GridControl1_ProcessGridKey;
            ColumnView columnView = gridControl1.MainView as ColumnView;
            columnView.OptionsSelection.MultiSelect = true;

            var gird = sender as GridControl;
            var view = gird.FocusedView as GridView;
            //if (e.KeyData = Keys.Delete) {
                columnView.DeleteSelectedRows();
                e.Handled = true;
           // }           

        }

    }
}
