using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using ProjectBNG.Models;

namespace ProjectBNG
{
    public partial class frmNoinhan : Form
    {
        public frmNoinhan()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.NoiNhans.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    noiNhansBindingSource.DataSource = dbContext.NoiNhans.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private bool CheckExistForm(string name)
        {
            bool check = false;
            foreach (Form frm in this.MdiChildren)
            {
                if (frm.Name == name)
                {
                    check = true;
                    break;
                }
            }
            return check;
        }

        private void ActiveChildForm(string name)
        {
            foreach (Form frm in this.MdiChildren)
            {
                if (frm.Name == name)
                {
                    frm.Activate();
                    break;
                }
            }
        }

        private void btnThemNoiNhan_Click(object sender, EventArgs e)
        {
            if (!CheckExistForm("frmThongTinNoiNhan"))
            {
                frmThongTinNoiNhan fthongtinnoinhan = new frmThongTinNoiNhan();
                //fthongtinnoinhan.MdiParent = this.MdiParent;
                fthongtinnoinhan.ShowDialog(this);
            }
            else
            {
                ActiveChildForm("frmThongTinNoiNhan");
            }

        }
        private SMMgEntities publicLoai;
        private void frmNoinhan_Load(object sender, EventArgs e)
        {
            this.gridView1.OptionsView.ShowGroupedColumns = true;
            publicLoai = new SMMgEntities();
            cmbLoai.DataSource = publicLoai.PhanLoaiNoiNhans.ToList();
            cmbLoai.DisplayMember = "PhanLoai";
            cmbLoai.Invalidate();
        }
        public void reloadFormNoiNhan()
        {
            //if
            //this.Close();
            ////this.Refresh();
            //this.Show();
        }
    }
}
