using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using ProjectBNG.Models;

namespace ProjectBNG
{
    public partial class frmNoinhan : Form
    {
        public frmNoinhan()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.NoiNhans.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                noiNhansBindingSource.DataSource = dbContext.NoiNhans.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        private bool CheckExistForm(string name)
        {
            bool check = false;
            foreach (Form frm in this.MdiChildren)
            {
                if (frm.Name == name)
                {
                    check = true;
                    break;
                }
            }
            return check;
        }

        private void ActiveChildForm(string name)
        {
            foreach (Form frm in this.MdiChildren)
            {
                if (frm.Name == name)
                {
                    frm.Activate();
                    break;
                }
            }
        }
        SMMgEntities db = new SMMgEntities();
        private void btnThemNoiNhan_Click(object sender, EventArgs e)
        {
            if (!CheckExistForm("frmThongTinNoiNhan"))
            {
                frmThongTinNoiNhan fthongtinnoinhan = new frmThongTinNoiNhan(() =>
                {

                    gridControl1.DataSource = db.NoiNhans.ToList();
                    gridControl1.RefreshDataSource();
                    return false;
                });
                //fthongtinnoinhan.MdiParent = this.MdiParent;
                fthongtinnoinhan.ShowDialog(this);
            }
            else
            {
                ActiveChildForm("frmThongTinNoiNhan");
            }

        }
        private SMMgEntities publicLoai;
        public void frmNoinhan_Load(object sender, EventArgs e)
        {
            this.gridView1.OptionsView.ShowGroupedColumns = true;
            publicLoai = new SMMgEntities();

            cmbLoai.DataSource = publicLoai.Loais.ToList();
            cmbLoai.ValueMember = "id";
            cmbLoai.DisplayMember = "TenLoai";

            cmbLoai.Invalidate();
            gridControl1_Load(sender, e);
        }
        public void reloadFormNoiNhan()
        {

        }

        public void gridControl1_Load(object sender, EventArgs e)
        {

            gridControl1.DataSource = db.NoiNhans.ToList();
            gridControl1.RefreshDataSource();
        }

        private void btnXoa_Click(object sender, EventArgs e)
        {

            DialogResult wr = MessageBox.Show("Xóa nơi nhận này ?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (wr == DialogResult.Yes)
            {
                NoiNhan delNoiNhan = new NoiNhan();
                try
                {

                    delNoiNhan.id = int.Parse(gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "id").ToString());
                    deleteNoiNhan(delNoiNhan);
                    MessageBox.Show("Xóa thành công ", "Thông báo");
                }
                catch
                {
                }
                gridControl1_Load(sender, e);
            }
            void deleteNoiNhan(NoiNhan noiNhan)
            {
                NoiNhan d = db.NoiNhans.Find(noiNhan.id);
                db.NoiNhans.Remove(d);
                db.SaveChanges();
            }
        }

        private void frmNoinhan_FormClosing(object sender, FormClosingEventArgs e)
        {
            gridControl1_Load(sender, e);
        }

        private void frmNoinhan_Activated(object sender, EventArgs e)
        {
            gridControl1_Load(sender, e);
        }
        private void btnTimKiem_Click(object sender, EventArgs e)
        {
            SMMgEntities db = new SMMgEntities();
            try
            {
                if (tbTenNoiNhanTimKiem.Text == "" && (cmbLoai.Text == "Nội bộ" || cmbLoai.Text == "Bên ngoài"))
                {
                    gridControl1.DataSource = db.NoiNhans
                            .Where(x => x.Loai == cmbLoai.Text)
                            .Select(x => new
                            {
                                MaNoiNhan = x.MaNoiNhan,
                                TenNoiNhan = x.TenNoiNhan,
                                SoBaoMat = x.SoBaoMat,
                                Loai = x.Loai
                            }).ToList();
                    gridControl1.RefreshDataSource();
                }
                else if (tbTenNoiNhanTimKiem.Text == "" && cmbLoai.Text == "Tất cả")
                {
                    gridControl1.DataSource = db.NoiNhans.ToList();
                    gridControl1.RefreshDataSource();
                }
                else if (tbTenNoiNhanTimKiem.Text != "" && (cmbLoai.Text == "Nội bộ" || cmbLoai.Text == "Bên ngoài"))
                {
                    gridControl1.DataSource = db.NoiNhans
                                .Where(x => x.TenNoiNhan == tbTenNoiNhanTimKiem.Text && x.Loai == cmbLoai.Text)
                                .Select(x => new
                                {
                                    MaNoiNhan = x.MaNoiNhan,
                                    TenNoiNhan = x.TenNoiNhan,
                                    SoBaoMat = x.SoBaoMat,
                                    Loai = x.Loai
                                }).ToList();
                    gridControl1.RefreshDataSource();
                }
                else if (tbTenNoiNhanTimKiem.Text != "" && cmbLoai.Text == "Tất cả")
                {
                    gridControl1.DataSource = db.NoiNhans
                        .Where(x => x.TenNoiNhan == tbTenNoiNhanTimKiem.Text)
                        .Select(x => new
                        {
                            MaNoiNhan = x.MaNoiNhan,
                            TenNoiNhan = x.TenNoiNhan,
                            SoBaoMat = x.SoBaoMat,
                            Loai = x.Loai
                        }).ToList();
                    gridControl1.RefreshDataSource();
                }
            }
            catch
            {
            }
        }
    }
}
