using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using ProjectBNG.Models;

namespace ProjectBNG
{
    public partial class frmNguoiKy : Form
    {
        public frmNguoiKy()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ProjectBNG.Models.SMMgEntities dbContext = new ProjectBNG.Models.SMMgEntities();

            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.NguoiKies.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                nguoiKiesBindingSource1.DataSource = dbContext.NguoiKies.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        SMMgEntities db = new SMMgEntities();

        private bool CheckExistForm(string name)
        {
            bool check = false;
            foreach (Form frm in this.MdiChildren)
            {
                if (frm.Name == name)
                {
                    check = true;
                    break;
                }
            }
            return check;
        }

        private void ActiveChildForm(string name)
        {
            foreach (Form frm in this.MdiChildren)
            {
                if (frm.Name == name)
                {
                    frm.Activate();
                    break;
                }
            }
        }

        private void button4_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            if (!CheckExistForm("frmThemNguoiKy"))
            {
                frmThemNguoiKy fthemsuangky = new frmThemNguoiKy(() => {
                    gridControlNguoiKy.DataSource = db.NguoiKies.ToList();
                    gridControlNguoiKy.RefreshDataSource();
                    return false;
                });
                //fthemsuangky.MdiParent = this.MdiParent;
                fthemsuangky.Show();
            }
            else
            {
                ActiveChildForm("frmThemNguoiKy");
            }
        }


        public delegate void PassData(NguoiKy nk);
        public PassData passData;

        public void btnSuaNgKy_Click(object sender, EventArgs e)
        {
        // lay thong tin id cua nguoi ky
        NguoiKy getNguoiKy = new NguoiKy();
            if (!CheckExistForm("frmThemNguoiKy"))
            {
                

                try
                {
                    getNguoiKy = (NguoiKy)gridViewNguoiKy.GetRow(gridViewNguoiKy.FocusedRowHandle);

                        //int.Parse(gridViewNguoiKy.GetRowCellValue(gridViewNguoiKy.FocusedRowHandle, "id").ToString());
                }
                catch { }
                //int idNguoiKySelected;
                //idNguoiKySelected = getNguoiKy.id;
                //fSuaNguoiKy.getIdSelect(getNguoiKy);
                frmSuaNguoiKy fSuaNguoiKy = new frmSuaNguoiKy(() => {
                    gridControlNguoiKy.DataSource = db.NguoiKies.ToList();
                    gridControlNguoiKy.RefreshDataSource();
                    return false;
                }, getNguoiKy);
                // ok done =)))))
                fSuaNguoiKy.Show();
                
            }
            else
            {
                ActiveChildForm("frmThemSuaNguoiKy");
            }
        }

        private void btnXoaNgKy_Click(object sender, EventArgs e)
        {
            NguoiKy delNguoiKy = new NguoiKy();
            try
            {
                delNguoiKy.id = int.Parse(gridViewNguoiKy.GetRowCellValue(gridViewNguoiKy.FocusedRowHandle, "id").ToString());
            }
            catch { }
            NguoiKy d = db.NguoiKies.Find(delNguoiKy.id);
            db.NguoiKies.Remove(d);
            db.SaveChanges();
            //deleteNguoiKy(delNguoiKy);
            frmNguoiKy_Load(sender,e);
            MessageBox.Show("Đã xóa thành công ", "Thông báo");
            //void deleteNguoiKy(NguoiKy idNgKy)
            //{
                
            //    NguoiKy d= db.NguoiKies.Find(idNgKy.id);
            //    db.NguoiKies.Remove(d);
            //    db.SaveChanges();
            //}
        }

        private void frmNguoiKy_Load(object sender, EventArgs e)
        { 
                gridControlNguoiKy.DataSource = db.NguoiKies.ToList();
                gridControlNguoiKy.RefreshDataSource(); 
        }
    }
}
